config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'welcome', to: 'welcome#home'

  get 'about', to: 'welcome#about'

  get 'sessions', to: 'sessions#destroy'

  put 'event/:id/join', to: 'events#join', as: 'join'

  delete 'event/:id/cancel_join', to: 'events#cancel_join', as: 'cancel_join'

  resources :sessions

  # match '/app/github/callback', to: 'sessions#create', via: [:get, :post] 

  resources :lang_topics,  only: [:new, :create]
  resources :user_events,  only: [:new, :create, :destroy]
  resources :events
  resources :topics, only: [:show, :new, :create, :index]
  resources :languages, only: [:index, :show]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :lang_topics
    has_many :events, through: :lang_topics

    def self.sorted_list
        all.sort {|a, b| a.name <=> b.name}
    end

    def topics
        self.lang_topics.map { |lt| lt.topic }.sort { |a,b| a.title <=> b.title } 
    end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

    def index
        @languages = Language.all
    end

    def show
        @language = Language.find(params[:id])
    end
    
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/index.html.erb
<body class='languages'> 

<div style="margin-top:40vh;">
<h1>Events by Language</h1> 

<div class="lang-list">

<ul>
    <% @languages.sorted_list.each do |lang|%>
        <li><%= link_to lang.name, language_path(lang) %></li><br>
    <% end %>
</ul>

</div>

</div>

</body>

app/views/languages/show.html.erb
<div class="show-lang">


<%= image_tag @language.img_url, :size => "180x180" %>

<h3 style="text-align:center; margin-top:100px;"><%= @language.description %></h3><br>
<br>


<uL>
    <% @language.topics.each do |topic| %>
        <li><%= link_to topic.title, events_path(:language => @language, :topic => topic) %><br><br>
    <% end %>
</ul>

<h2 style="text-align: center;"><%= link_to "#{@language.name} Events", events_path(:language => @language) %></h2>

</div>