config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'welcome', to: 'welcome#home'

  get 'about', to: 'welcome#about'

  get 'sessions', to: 'sessions#destroy'

  put 'event/:id/join', to: 'events#join', as: 'join'

  delete 'event/:id/cancel_join', to: 'events#cancel_join', as: 'cancel_join'

  resources :sessions

  # match '/app/github/callback', to: 'sessions#create', via: [:get, :post] 

  resources :lang_topics,  only: [:new, :create]
  resources :user_events,  only: [:new, :create, :destroy]
  resources :events
  resources :topics, only: [:show, :new, :create, :index]
  resources :languages, only: [:index, :show]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  before_action :require_logged_in

  def home
  end

  def about
  end

end

app/views/welcome/about.html.erb
<body class="welcome">

<div class="dashboard">

<div style="text-align:center; color:white; 
background-color: rgba(52, 52, 52, 0.8); position: absolute; 
top: 20vh; width: 100vw">

<h3>
The Coding Collective is on online platform where software developers and enthusiasts can connect and grow together!
</h3>

<div style="font-size:20px;">
<p>
Whether you're looking to join a new networking group or looking to expand your knowledge, this is the place for you. <br/><br/>
Visit our events page to view and register for upcoming events.<br/><br/>
You can narrow down your search by browsing events by language as well. <br/><br/>
In recognition of every programmer's unique background and experience, we allow any user to create thier own event and share their knowledge while connecting with like-minded individuals.<br/><br/>
***We only ask that all events remain inclusive and refrain from political, religious or other divisive topics. We're here to open up a friendly and inviting space for all.***<br/><br/></p>
<p>Learned something new? We want to hear from you. <a href="mailto:managment@codingcollab.com" style="color:lightblue">Email us!</a><br/>
Happy coding!<br/>
</p>

</div>
</div>
</div>

</body>

app/views/welcome/home.html.erb
<body class="welcome">

<div class="dashboard">

<% if flash[:notice] %>
    <% flash[:notice].each do |notice| %>
        <p style="color:red;"><%= notice %></p>
    <% end %>
<% end %>

<h3 style="margin-left:10%">Welcome back, <%= current_user[:name] %>!</h3>

<div class="column-wrapper">

<div class="row">

<div class="columns">

<div class="column1">

<h4>You have <%= pluralize( current_user.events_attending.count, 'upcoming event') %>.</h4>

<ul>
    <% if current_user.events_attending.any? %>
    <% current_user.events_attending.each do |ue| %>
    <li><%= link_to ue.event.title, event_path(ue.event) %></li><br>
    <% end %>
    <% end %>
</ul>

</div>

</div>

<div class="column2">

<h4>Currently hosting <%= pluralize( current_user.events_hosting.count, 'upcoming event') %>.</h4>

<ul>
    <% if current_user.events_hosting.any? %>
    <% current_user.events_hosting.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li><br>
    <% end %>
    <% end %>
</ul>

</div>

</div>

<div>

</div>

</div>

</body>