config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'welcome', to: 'welcome#home'

  get 'about', to: 'welcome#about'

  get 'sessions', to: 'sessions#destroy'

  put 'event/:id/join', to: 'events#join', as: 'join'

  delete 'event/:id/cancel_join', to: 'events#cancel_join', as: 'cancel_join'

  resources :sessions

  # match '/app/github/callback', to: 'sessions#create', via: [:get, :post] 

  resources :lang_topics,  only: [:new, :create]
  resources :user_events,  only: [:new, :create, :destroy]
  resources :events
  resources :topics, only: [:show, :new, :create, :index]
  resources :languages, only: [:index, :show]
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :host, :class_name => :User
    belongs_to :lang_topic
    has_many :participants, :class_name => :User

    validates_date :date, on_or_after: lambda { Date.current }, on_or_after_message: "of Meetup cannot be in the past."
    
    attr_reader :language, :topic

    @@times = ["12:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM", "12:00 PM"]
    
    def attendees_count
        user_events = UserEvent.all.select {|ue| ue.event_id == self.id}
        user_events.map {|event| event.participant_id}.count
    end

    def display_date
        split_date = self.date.to_s.split("-")
        month = split_date[1]
        day = split_date[2]
        year = split_date[0]
        return "#{month}/#{day}/#{year}"
    end


    def self.sort_by_date
        all.sort { |a,b| [a.date, a.time.to_time] <=> [b.date, b.time.to_time] }
    end

    def language
        self.lang_topic.language
    end

    def topic
        self.lang_topic.topic
    end

    def self.times
        @@times
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :require_logged_in
     
    def index
        if params[:topic] && !params[:language]
            @events = Event.sort_by_date.select do |e|
                e.topic == Topic.find(params[:topic])
            end
            @topic = Topic.find(params[:topic])
        elsif params[:topic]
            @events = Event.sort_by_date.select do |e|
                if e.language == Language.find(params[:language])
                    e.topic == Topic.find(params[:topic])
                end
            end
            @lang = Language.all.find(params[:language])
            @topic = Topic.all.find(params[:topic])
        elsif params[:language]
            @events = Event.sort_by_date.select do |e|
                e.language == Language.find(params[:language])
            end
            @lang = Language.all.find(params[:language])
        else
            @events = Event.sort_by_date
        end
    end
    
    def show
        @event = Event.find(params[:id])
        @language = @event.language
        @topic = @event.topic
        @host = User.find(@event.host_id)
        @user_event = UserEvent.find_by(event_id: params[:id])
    end

    def new
        @event = Event.new
        @lang_topics = LangTopic.all
        @times = Event.times
    end

    def create
        @event = Event.create(event_params.merge(:host_id => session[:user_id]))
        if @event.save
            redirect_to events_path(@event)
        elsif  
            flash[:errors] = @event.errors.full_messages
            redirect_to new_event_path
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @lang_topics = LangTopic.all
        @event = Event.find(params[:id])
        @event.update(event_params)
        flash[:success] = ["#{@event.title} has been updated."]
        redirect_to event_path(@event)
    end

    def join
        @event = Event.find(params[:id])
        @user_event = UserEvent.create(:event_id => @event.id, :participant_id => current_user.id)
            if @user_event.save
                current_user.user_events << @user_event
                redirect_to controller: 'welcome', action: 'home'
            else 
                flash[:errors] = ["You've already registered for this event!"]
                redirect_to event_path
        end
    end

    def cancel_join
        @event = Event.find(params[:id])
        @user_event = UserEvent.find_by(event_id: @event.id)
        current_user.user_events.delete_by(params[:event_id])
        redirect_to controller:'welcome', action: 'home'
    end

    def destroy
        @event = Event.find(params[:id])
        @event.delete
        flash[:notice] = ["#{@event.title} has been deleted."]
        redirect_to controller: 'welcome', action: 'home'
    end

    private

    def event_params
        params.require(:event).permit(:title, :lang_topic_id, :location, :date, :time)
    end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<body class="container events"> 

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p style="color:red;"><%= error %></p>
    <% end %>
<% end %>

<div class="form" style="background-color: rgba(52, 52, 52, 0.8); position: absolute; top: 20vh; width: 100vw">

<%= form_for @event, method: 'patch' do |f| %>


    <h2 style="color:white;text-shadow: 2px 2px #000;" >Update Your Meetup</h2><br>

    <%= f.text_field :title %><br><br>

    <%= f.collection_select :lang_topic_id, LangTopic.sorted_list, :id, :display_lt %><br><br><br>

    <%= f.text_field :location %><br><br>

    <%= f.date_field :date %><br><br>

    <%= f.select :time, options_for_select(Event.times) %><br><br><br></p>


    <%= f.submit 'Update Event' %><br><br>

<% end %>


<div class = "form">

</body>

app/views/events/index.html.erb
<body class="languages">

<% if @topic && !@lang %>
    <h1><%= @topic.title %> Events</h1>
<% elsif @topic %>
    <h1><%= @lang.name + " - " + @topic.title %> Events</h1>
<% elsif @lang %>
    <h1>Upcoming <%= @lang.name %> Events</h1>
<% end %>

<div class="flex-container" style="margin-top:40vh">

<% if @topic && !@lang %>
    <ul style="margin-top:250px; margin-bottom:290px;">
        <% @events.each do |event|%>
        <% if event.date >= Date.today %>
            <dl><dt><%= link_to event.title, event_path(event) %></dt>
            <dt>Location: <%= event.location %></dt>
            <dt>Date: <%= event.display_date %> Time: <%= event.time %></dt>
            <dt><%= image_tag event.language.img_url, :size => "30x30" %></dt>
            </dl><br>
        <% end %>
        <% end %>
    </ul>

<% elsif @topic %>
    <ul style="margin-top:250px; margin-bottom:290px;">
        <% @events.each do |event|%>
        <% if event.date >= Date.today %>
            <dl><dt><%= link_to event.title, event_path(event) %></dt>
            <dt>Location: <%= event.location %></dt>
            <dt>Date: <%= event.display_date %> Time: <%= event.time %></dt>
            </dl><br>
        <% end %>
        <% end %>
    </ul>
<% elsif @lang %>
    <ul style="margin-top:250px; margin-bottom:290px;">
        <% @events.each do |event|%>
        <% if event.date >= Date.today %>
            <dl><dt><%= link_to event.title, event_path(event) %></dt>
            <dt><%= event.topic.title %></dt>
            <dt>Location: <%= event.location %></dt>
            <dt>Date: <%= event.display_date %> Time: <%= event.time %></dt>
            </dl><br>
        <% end %>
        <% end %>
    </ul>
<% else %>
    <ul style="margin-top:250px; margin-bottom:290px;">
        <% @events.each do |event|%>
        <% if event.date >= Date.today %>
            <dl><dt><%= link_to event.title, event_path(event) %></dt>  
                <dt><%= event.language.name %> - <%= event.topic.title %></dt>
                <dt>Location: <%= event.location %></dt>
                <dt>Date: <%= event.display_date %> Time: <%= event.time %></dt>
                <dt><%= image_tag event.language.img_url, :size => "30x30" %></dt>
            </dl><br>
        <% end %>
        <% end %>
    </ul>
<% end %>

</div>

</body>

app/views/events/new.html.erb
 <body class="events"> 

<div class="form" style="background-color: rgba(52, 52, 52, 0.8); position: absolute; top: 20vh; width: 100vw">

<h3 style="color:white;text-shadow: 2px 2px #000;"><em>Ready to host an event of your own?</em></h3>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p style="color:red;"><%= error %></p>
    <% end %>
<% end %>

<%= form_for @event do |f| %>


    <h2 style="color:white;text-shadow: 2px 2px #000;" >List Your Meetup</h2><br>

    <%= f.text_field :title, placeholder: 'Enter Title' %><br><br>

    <%= f.collection_select :lang_topic_id, @lang_topics.sorted_list, :id, :display_lt %><br><br><br>

    <%= f.text_field :location, placeholder: 'Location' %><br><br>

    <%= f.date_field :date %><br><br>

    <%= f.select :time, options_for_select(@times) %><br><br><br></p>>


    <%= f.submit 'Create Event' %><br><br>

<% end %>


</div>

</body>

app/views/events/show.html.erb
<body class="event-show">

<h1><%= @event.title %><br></h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p style="color:red;"><%= error %></p>
    <% end %>
<% end %>

<% if flash[:success] %>
    <% flash[:success].each do |success| %>
        <p style="color:green;"><%= success %></p>
    <% end %>
<% end %>


<%= link_to @language.name, language_path(@language) %><br>

Topic: <%= @topic.title %><br>
Location: <%= @event.location %><br>
<%= @event.display_date %><br>
<%= @event.time %><br>
<em>Hosted by: <%= @host.name %><br></em>

<% if !current_user.events_hosting.include?(@event) %>
  <%= button_to 'register', join_path(@event), method:'put'%><br>
<% end %><br>

<% if current_user.events_attending.include?(@user_event) %>
    <%= button_to 'cancel registeration', cancel_join_path(@event), method:'delete'%><br>
<% end %><br>

<% if current_user.events_hosting.include?(@event) %>
  <%= button_to "update event", edit_event_path, method:'get'%><br>
  <%= button_to "delete", {:controller => :events,
      :action => 'destroy', :id => @event.id }, :method => :delete %>

<% end %><br>

There is <%= pluralize( @event.attendees_count, 'person') %> registered for this event!

</body>